# Generic Settings
version: '{build}-{branch}'

matrix:
  fast_finish: true

# Build Image & Environment
platform: x64

image:
  - Visual Studio 2017

environment:
  CMAKE_SYSTEM_VERSION: 10.0.17134.0
  PACKAGE_PREFIX: obs-ffmpeg-encoder
  INNOSETUP_URL: http://www.jrsoftware.org/download.php/is.exe
  CURL_VERSION: 7.39.0

# Resource Cache
cache:
  - inno.exe
  - build/32/libobs-download
  - build/32/libobs-src
  - build/64/libobs-download
  - build/64/libobs-src

# Building  
install:
- cmd: ci/appveyor-install.bat

build_script:
- cmd: node ci/appveyor-build.js

after_build:
- cmd: ci/appveyor-package.bat

# Testing
test: off

# Artifacts
artifacts:
  - path: build/obs-ffmpeg-encoder-*.zip
  - path: build/obs-ffmpeg-encoder-*.7z
  - path: build/obs-ffmpeg-encoder-*.exe

# Deploying
deploy:
  - provider: GitHub
    auth_token:
      secure: diGN1FzupARljI1iJsiAdZHut8aXODkUC6YDDi2oDRikEp5Ic8kQd8SSRDyA4pAJ
    draft: true
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true

# Notifications
notifications:
  - provider: Webhook
    url: 
      secure: PTtt5ALhmK0q42jYyx4/Qa1Uf18+gLMXKGdzJjDISJt8IE/K0Zyp58UYmDDbbyLp4pBRf/Ylj8rn/zYL/mqBoDVRIH5zasPqIvBD0ZhtvNjTOxQ3QoRkAmxgpWeMowm3A3I1rLizA2H4EctPpoAJGrvQ1G2HEYn9tVsGYeetFTo=
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
    body: >-
      {
        "content": "**Build {{status}}**: [{{commitId}}] {{commitMessage}}\nBy {{commitAuthor}} on {{commitDate}}\n{{buildUrl}}"
      }
