name: CI

on: [push, pull_request]

jobs:
  windows:
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
        include:
          - os: windows-2016
            generator_32: "Visual Studio 15 2017"
            generator_64: "Visual Studio 15 2017"
            sysversion: "10.0.17763.0"
          - os: windows-2019
            generator_32: "Visual Studio 16 2019"
            generator_64: "Visual Studio 16 2019"
            sysversion: "10.0.18362.0"
    runs-on: ${{ matrix.os }}
    steps:
    - name: "Clone Repository"
      uses: actions/checkout@v1
    - name: Install Node.JS 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Configure & Compile
      env:
        CMAKE_GENERATOR_32: ${{ matrix.generator_32 }}
        CMAKE_GENERATOR_64: ${{ matrix.generator_64 }}
        CMAKE_SYSTEM_VERSION: ${{ matrix.sysversion }}
      run: node ./ci/builder.js
    - name: Package
      env:
        CMAKE_GENERATOR_32: ${{ matrix.generator_32 }}
        CMAKE_GENERATOR_64: ${{ matrix.generator_64 }}
      run: |
        mkdir build/package
        node ./ci/packager.js
    - name: "Package Installer (Prereqs)"
      run: |
        curl "-kL" "https://cdn.xaymar.com/ci/innosetup-6.0.3.exe" "-f" "--retry" "5" "-o" "inno.exe"
        .\inno.exe /VERYSILENT /SP- /SUPPRESSMSGBOXES /NORESTART
    - name: "Package Installer (Compile)"
      run: |
        & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' /Qp ".\build\64\installer.iss"
    - name: "Upload Artifacts"
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: build/package